import json
import urllib.parse

# Read existing file
with open("C:/Users/user/kotohira-quiz/web/public/data/english_questions.json", "r", encoding="utf-8") as f:
    data = json.load(f)

existing = data["questions"]
print(f"Existing questions: {len(existing)}")

# Verify existing words
existing_words = set()
for q in existing:
    existing_words.add(q["word"])
print(f"Existing unique words: {len(existing_words)}")

# 250 new words
new_words = [
    # === Business/Work (20) ===
    ("collaborate", "kəlǽbərèit", "協力する", "B1",
     ["A. 崩壊する", "B. 協力する", "C. 収集する", "D. 比較する"], "B",
     ["A. celebrate", "B. collaborate", "C. calculate", "D. calibrate"], "B",
     "We need to collaborate on this project.（このプロジェクトで協力する必要がある。）",
     "Let's collaborate with the overseas team.（海外チームと協力しよう。）"),
    ("delegate", "déləgèit", "委任する", "B1",
     ["A. 削除する", "B. 配達する", "C. 委任する", "D. 装飾する"], "C",
     ["A. dedicate", "B. delicate", "C. delegate", "D. deliberate"], "C",
     "A good leader knows how to delegate tasks.（良いリーダーは仕事を委任する方法を知っている。）",
     "She learned to delegate responsibilities to her team.（彼女はチームに責任を委任することを学んだ。）"),
    ("promote", "prəmóut", "促進する", "B1",
     ["A. 促進する", "B. 約束する", "C. 保護する", "D. 抗議する"], "A",
     ["A. promote", "B. promise", "C. propose", "D. provoke"], "A",
     "The company promotes a healthy work environment.（その会社は健全な職場環境を促進している。）",
     "We should promote teamwork in the office.（職場でチームワークを促進すべきだ。）"),
    ("resign", "rizáin", "辞職する", "B1",
     ["A. 設計する", "B. 署名する", "C. 辞職する", "D. 拒否する"], "C",
     ["A. design", "B. assign", "C. resign", "D. consign"], "C",
     "He decided to resign from his position.（彼はその職を辞職することを決めた。）",
     "She plans to resign at the end of the month.（彼女は月末に辞職する予定だ。）"),
    ("submit", "səbmít", "提出する", "A2",
     ["A. 提出する", "B. 服従する", "C. 代用する", "D. 引き算する"], "A",
     ["A. summit", "B. submit", "C. permit", "D. commit"], "B",
     "Please submit your report by Friday.（金曜日までに報告書を提出してください。）",
     "You must submit the form online.（オンラインでフォームを提出しなければならない。）"),
    ("achieve", "ətʃíːv", "達成する", "A2",
     ["A. 信じる", "B. 受け取る", "C. 達成する", "D. 欺く"], "C",
     ["A. achieve", "B. receive", "C. believe", "D. relieve"], "A",
     "She achieved her goal of running a marathon.（彼女はマラソンを走るという目標を達成した。）",
     "He worked hard to achieve success.（彼は成功を達成するために懸命に働いた。）"),
    ("recruit", "rikrúːt", "採用する", "B1",
     ["A. 採用する", "B. 回復する", "C. 再利用する", "D. 改修する"], "A",
     ["A. recruit", "B. receipt", "C. recite", "D. retreat"], "A",
     "The company is recruiting new employees.（その会社は新しい従業員を採用している。）",
     "We need to recruit more staff this year.（今年はもっとスタッフを採用する必要がある。）"),
    ("supervise", "súːpərvàiz", "監督する", "B1",
     ["A. 供給する", "B. 驚かす", "C. 監督する", "D. 生き残る"], "C",
     ["A. surprise", "B. supervise", "C. summarize", "D. subsidize"], "B",
     "She supervises a team of ten people.（彼女は10人のチームを監督している。）",
     "Who will supervise the construction work?（誰が建設作業を監督するのか？）"),
    ("implement", "ímpləmənt", "実行する", "B1",
     ["A. 輸入する", "B. 暗示する", "C. 実行する", "D. 改善する"], "C",
     ["A. implement", "B. imply", "C. import", "D. improve"], "A",
     "We plan to implement the new system next month.（来月、新しいシステムを実行する予定だ。）",
     "It is time to implement the strategy.（戦略を実行する時だ。）"),
    ("allocate", "ǽləkèit", "割り当てる", "B1",
     ["A. 配置する", "B. 割り当てる", "C. 軽減する", "D. 評価する"], "B",
     ["A. allocate", "B. advocate", "C. alleviate", "D. alternate"], "A",
     "The manager will allocate resources to each team.（マネージャーが各チームに資源を割り当てる。）",
     "We must allocate the budget carefully.（予算を慎重に割り当てなければならない。）"),
    ("compensate", "kɑ́mpənsèit", "補償する", "B1",
     ["A. 競争する", "B. 構成する", "C. 補償する", "D. 複雑にする"], "C",
     ["A. complicate", "B. compensate", "C. compromise", "D. concentrate"], "B",
     "The company will compensate for the damage.（会社はその損害を補償する。）",
     "They agreed to compensate the affected workers.（影響を受けた労働者を補償することに同意した。）"),
    ("assess", "əsés", "評価する", "B1",
     ["A. 評価する", "B. 仮定する", "C. 支援する", "D. 保証する"], "A",
     ["A. assess", "B. access", "C. assist", "D. assert"], "A",
     "We need to assess the risks before starting.（始める前にリスクを評価する必要がある。）",
     "The teacher will assess your performance.（先生があなたの成績を評価する。）"),
    ("comply", "kəmplái", "従う", "B1",
     ["A. 不平を言う", "B. 完了する", "C. 従う", "D. 編集する"], "C",
     ["A. comply", "B. compile", "C. compete", "D. compare"], "A",
     "All employees must comply with company rules.（全従業員は会社の規則に従わなければならない。）",
     "You must comply with local regulations.（地域の規制に従わなければならない。）"),
    ("consult", "kənsʌ́lt", "相談する", "A2",
     ["A. 消費する", "B. 含む", "C. 相談する", "D. 続ける"], "C",
     ["A. consume", "B. consult", "C. consist", "D. conduct"], "B",
     "You should consult a doctor about your symptoms.（症状について医者に相談すべきだ。）",
     "Please consult your supervisor before making changes.（変更前に上司に相談してください。）"),
    ("dismiss", "dismís", "却下する", "B1",
     ["A. 却下する", "B. 発見する", "C. 議論する", "D. 展示する"], "A",
     ["A. dismiss", "B. discuss", "C. display", "D. dispute"], "A",
     "The judge dismissed the case.（裁判官はその訴訟を却下した。）",
     "Don't dismiss his idea without consideration.（彼の考えを検討せずに却下しないで。）"),
    ("prospect", "prɑ́spekt", "見込み", "B1",
     ["A. 計画書", "B. 保護者", "C. 見込み", "D. 手順書"], "C",
     ["A. project", "B. prospect", "C. protest", "D. protect"], "B",
     "There is a good prospect of success.（成功の見込みは十分にある。）",
     "The job prospects in this field are excellent.（この分野の就職の見込みは素晴らしい。）"),
    ("revenue", "révənjùː", "収益", "B1",
     ["A. 復讐心", "B. 収益額", "C. 再開日", "D. 調査費"], "B",
     ["A. revenue", "B. revenge", "C. reverse", "D. revolve"], "A",
     "The company's annual revenue increased by 20%.（会社の年間収益は20%増加した。）",
     "Online sales account for half of total revenue.（オンライン販売が総収益の半分を占める。）"),
    ("workforce", "wə́ːrkfɔːrs", "労働力", "B1",
     ["A. 労働力", "B. 作業場", "C. 勤務表", "D. 職業訓練"], "A",
     ["A. workplace", "B. workshop", "C. workforce", "D. workload"], "C",
     "The company has a diverse workforce.（その会社は多様な労働力を持っている。）",
     "Japan's workforce is shrinking due to aging.（日本の労働力は高齢化により縮小している。）"),
    ("agenda", "ədʒéndə", "議題", "B1",
     ["A. 代理人", "B. 議題一覧", "C. 集合体", "D. 同意書"], "B",
     ["A. agenda", "B. agency", "C. agent", "D. agree"], "A",
     "Let's move on to the next item on the agenda.（議題の次の項目に進みましょう。）",
     "The meeting agenda has been distributed.（会議の議題が配布された。）"),
    ("welfare", "wélfɛər", "福祉", "B1",
     ["A. 豊かさ", "B. 福祉制度", "C. 戦争行為", "D. 天気予報"], "B",
     ["A. warfare", "B. welfare", "C. farewell", "D. weather"], "B",
     "The government is responsible for public welfare.（政府は公共の福祉に責任がある。）",
     "Child welfare is a top priority.（児童福祉は最優先事項だ。）"),
    # === Academic (19) ===
    ("hypothesis", "haipɑ́θəsis", "仮説", "B1",
     ["A. 仮説理論", "B. 低体温症", "C. 偽善行為", "D. 催眠術法"], "A",
     ["A. hypothesis", "B. hypocrisy", "C. hypnosis", "D. hyperbole"], "A",
     "The scientist tested her hypothesis.（その科学者は仮説を検証した。）",
     "We need to form a hypothesis before the experiment.（実験の前に仮説を立てる必要がある。）"),
    ("theory", "θíːəri", "理論", "A2",
     ["A. 治療法", "B. 理論体系", "C. 脅威度", "D. 劇場用語"], "B",
     ["A. therapy", "B. theory", "C. threat", "D. theater"], "B",
     "Einstein's theory of relativity changed physics.（アインシュタインの相対性理論は物理学を変えた。）",
     "That is an interesting theory.（それは興味深い理論だ。）"),
    ("analyze", "ǽnəlàiz", "分析する", "B1",
     ["A. 麻痺させる", "B. 類推する", "C. 分析する", "D. 告知する"], "C",
     ["A. analyze", "B. paralyze", "C. advertise", "D. apologize"], "A",
     "We need to analyze the data carefully.（データを慎重に分析する必要がある。）",
     "The team will analyze customer feedback.（チームが顧客のフィードバックを分析する。）"),
    ("conclusion", "kənklúːʒən", "結論", "A2",
     ["A. 混乱状態", "B. 接続先", "C. 結論内容", "D. 状態変化"], "C",
     ["A. confusion", "B. conclusion", "C. condition", "D. connection"], "B",
     "What conclusion did you reach?（どんな結論に達しましたか？）",
     "In conclusion, the experiment was successful.（結論として、実験は成功だった。）"),
    ("evidence", "évədəns", "証拠", "B1",
     ["A. 出来事", "B. 明白さ", "C. 証拠資料", "D. 進化過程"], "C",
     ["A. evidence", "B. evident", "C. event", "D. evolve"], "A",
     "There is strong evidence to support this claim.（この主張を裏付ける強力な証拠がある。）",
     "The police found new evidence at the scene.（警察は現場で新しい証拠を見つけた。）"),
    ("abstract", "ǽbstrækt", "抽象的な", "B1",
     ["A. 抽象的な", "B. 不在中の", "C. 吸収的な", "D. 豊富にある"], "A",
     ["A. attract", "B. abstract", "C. subtract", "D. distract"], "B",
     "The painting was very abstract.（その絵画はとても抽象的だった。）",
     "Abstract concepts are hard to explain to children.（抽象的な概念を子供に説明するのは難しい。）"),
    ("interpret", "intə́ːrprət", "解釈する", "B1",
     ["A. 中断する", "B. 解釈する", "C. 紹介する", "D. 統合する"], "B",
     ["A. interpret", "B. interrupt", "C. interact", "D. interfere"], "A",
     "How do you interpret this poem?（この詩をどう解釈しますか？）",
     "It is difficult to interpret ancient texts.（古代の文献を解釈するのは難しい。）"),
    ("phenomenon", "fənɑ́mənɑ̀n", "現象", "B1",
     ["A. 哲学概念", "B. 自然現象", "C. 写真技術", "D. 基盤施設"], "B",
     ["A. philosophy", "B. phenomenon", "C. photograph", "D. pharmacy"], "B",
     "The aurora is a beautiful natural phenomenon.（オーロラは美しい自然現象だ。）",
     "This phenomenon has been studied for decades.（この現象は何十年も研究されてきた。）"),
    ("category", "kǽtəgɔ̀ːri", "分類", "A2",
     ["A. 大聖堂", "B. 分類項目", "C. 触媒体", "D. 目録帳"], "B",
     ["A. category", "B. catalog", "C. cathedral", "D. cafeteria"], "A",
     "This book belongs to the fiction category.（この本はフィクションの分類に属する。）",
     "Please select the appropriate category.（適切な分類を選択してください。）"),
    ("consistent", "kənsístənt", "一貫した", "B1",
     ["A. 意識的な", "B. 継続的な", "C. 一貫した", "D. 相当な"], "C",
     ["A. confident", "B. conscious", "C. constant", "D. consistent"], "D",
     "Her performance has been consistent all year.（彼女の成績は一年中一貫していた。）",
     "Be consistent in applying the rules.（規則の適用に一貫性を持ちなさい。）"),
    ("valid", "vǽlid", "有効な", "B1",
     ["A. 貴重な", "B. 多様な", "C. 曖昧な", "D. 有効な"], "D",
     ["A. vivid", "B. valid", "C. void", "D. vapid"], "B",
     "Your passport is valid for ten years.（あなたのパスポートは10年間有効です。）",
     "That is a valid argument.（それは有効な議論だ。）"),
    ("criteria", "kraitíːriə", "基準", "B1",
     ["A. 批評文", "B. 危機的", "C. 基準事項", "D. 犯罪者"], "C",
     ["A. criteria", "B. critical", "C. criminal", "D. crisis"], "A",
     "The selection criteria are very strict.（選考基準はとても厳しい。）",
     "What criteria did you use?（どんな基準を使いましたか？）"),
    ("thesis", "θíːsis", "論文", "B1",
     ["A. 論文成果", "B. 主題歌", "C. 理論値", "D. 治療法"], "A",
     ["A. thesis", "B. theme", "C. theory", "D. therapy"], "A",
     "She is writing her master's thesis.（彼女は修士論文を書いている。）",
     "His thesis was about climate change.（彼の論文は気候変動についてだった。）"),
    ("relevant", "réləvənt", "関連のある", "B1",
     ["A. 信頼できる", "B. 関連のある", "C. 冗長である", "D. 消極的な"], "B",
     ["A. reluctant", "B. relevant", "C. reliant", "D. redundant"], "B",
     "Please provide relevant information only.（関連のある情報のみ提供してください。）",
     "This data is not relevant to our study.（このデータは我々の研究に関連がない。）"),
    ("objective", "əbdʒéktiv", "目的", "B1",
     ["A. 反対意見", "B. 障害物体", "C. 義務事項", "D. 目的目標"], "D",
     ["A. objection", "B. obstacle", "C. objective", "D. obligation"], "C",
     "Our main objective is to increase sales.（我々の主な目的は売上を増やすことだ。）",
     "What is the objective of this meeting?（この会議の目的は何ですか？）"),
    ("context", "kɑ́ntekst", "文脈", "B1",
     ["A. 内容物", "B. 文脈背景", "C. 競争相手", "D. 契約書"], "B",
     ["A. contest", "B. context", "C. contact", "D. content"], "B",
     "You need to understand the context of the story.（物語の文脈を理解する必要がある。）",
     "This word has a different meaning in context.（この単語は文脈の中で異なる意味を持つ。）"),
    ("method", "méθəd", "方法", "A2",
     ["A. 金属素材", "B. 方法手段", "C. 記憶力", "D. 精神的な"], "B",
     ["A. method", "B. mental", "C. medal", "D. memory"], "A",
     "This is an effective teaching method.（これは効果的な教育方法だ。）",
     "What method did you use to solve the problem?（その問題を解くのにどんな方法を使いましたか？）"),
    ("principal", "prínsəpəl", "主要な", "B1",
     ["A. 原則的な", "B. 王子様の", "C. 主要な", "D. 印刷用の"], "C",
     ["A. principle", "B. principal", "C. printer", "D. primary"], "B",
     "The principal reason for the delay was bad weather.（遅延の主要な理由は悪天候だった。）",
     "She is the principal investigator of this research.（彼女はこの研究の主要な調査員だ。）"),
    ("summarize", "sʌ́məràiz", "要約する", "B1",
     ["A. 監督する", "B. 推測する", "C. 要約する", "D. 供給する"], "C",
     ["A. supervise", "B. summarize", "C. speculate", "D. subsidize"], "B",
     "Can you summarize the article in three sentences?（その記事を3文で要約できますか？）",
     "Please summarize the main points.（要点を要約してください。）"),
    # === Health/Medical (18) ===
    ("diagnose", "dàiəgnóuz", "診断する", "B1",
     ["A. 対話する", "B. 診断する", "C. 分解する", "D. 不賛成だ"], "B",
     ["A. dialogue", "B. diagnose", "C. diagram", "D. disagree"], "B",
     "The doctor diagnosed the illness quickly.（医者はその病気を素早く診断した。）",
     "It can be difficult to diagnose rare diseases.（希少な病気を診断するのは難しいことがある。）"),
    ("therapy", "θérəpi", "療法", "B1",
     ["A. 理論体系", "B. 療法治療", "C. 脅威要因", "D. 主題内容"], "B",
     ["A. therapy", "B. theory", "C. threat", "D. thereby"], "A",
     "She is receiving physical therapy after surgery.（彼女は手術後に理学療法を受けている。）",
     "Music therapy can help reduce stress.（音楽療法はストレスを軽減するのに役立つ。）"),
    ("immune", "imjúːn", "免疫の", "B1",
     ["A. 巨大な", "B. 即座の", "C. 免疫の", "D. 不動の"], "C",
     ["A. immense", "B. immune", "C. immerse", "D. impact"], "B",
     "The vaccine strengthens the immune system.（ワクチンは免疫システムを強化する。）",
     "Children are not immune to stress.（子供もストレスに対して免疫があるわけではない。）"),
    ("chronic", "krɑ́nik", "慢性の", "B1",
     ["A. 年代順の", "B. 慢性的な", "C. 皮肉な", "D. 危機的な"], "B",
     ["A. chronic", "B. chronicle", "C. critical", "D. chemical"], "A",
     "He suffers from chronic back pain.（彼は慢性的な腰痛に苦しんでいる。）",
     "Chronic stress can cause health problems.（慢性的なストレスは健康問題を引き起こす。）"),
    ("surgery", "sə́ːrdʒəri", "手術", "A2",
     ["A. 調査活動", "B. 手術治療", "C. 表面状態", "D. 余剰分量"], "B",
     ["A. surgery", "B. surface", "C. surplus", "D. survey"], "A",
     "The surgery was successful.（手術は成功した。）",
     "She needs surgery on her knee.（彼女は膝の手術が必要だ。）"),
    ("infectious", "infékʃəs", "感染性の", "B1",
     ["A. 効果的な", "B. 感染性の", "C. 影響力の", "D. 非公式の"], "B",
     ["A. infectious", "B. effective", "C. influence", "D. informal"], "A",
     "The disease is highly infectious.（その病気は非常に感染性が高い。）",
     "Her laughter was infectious.（彼女の笑いは感染性があった。）"),
    ("dosage", "dóusidʒ", "投与量", "B1",
     ["A. 損害額", "B. 文書類", "C. 投与量", "D. 下水道"], "C",
     ["A. damage", "B. dosage", "C. dossier", "D. passage"], "B",
     "Do not exceed the recommended dosage.（推奨投与量を超えないでください。）",
     "The dosage depends on the patient's weight.（投与量は患者の体重によって異なる。）"),
    ("fatigue", "fətíːg", "疲労", "B1",
     ["A. 失敗談", "B. 運命論", "C. 疲労感", "D. 特徴点"], "C",
     ["A. fatigue", "B. feature", "C. failure", "D. fantasy"], "A",
     "Driver fatigue is a common cause of accidents.（運転者の疲労は事故の一般的な原因だ。）",
     "She felt extreme fatigue after the marathon.（マラソンの後、彼女は極度の疲労を感じた。）"),
    ("disorder", "disɔ́ːrdər", "障害", "B1",
     ["A. 割引額", "B. 発見物", "C. 不一致", "D. 障害症状"], "D",
     ["A. discount", "B. disorder", "C. discover", "D. disagree"], "B",
     "Anxiety disorder affects millions of people.（不安障害は何百万人もの人々に影響を与えている。）",
     "Sleep disorders are becoming more common.（睡眠障害がより一般的になっている。）"),
    ("remedy", "rémədi", "治療法", "B1",
     ["A. 記憶力", "B. 治療法", "C. 救済策", "D. 想起力"], "B",
     ["A. remedy", "B. memory", "C. remote", "D. remove"], "A",
     "There is no simple remedy for this condition.（この症状に対する簡単な治療法はない。）",
     "Home remedies can sometimes be effective.（民間の治療法が効果的なこともある。）"),
    ("obesity", "oubíːsəti", "肥満", "B1",
     ["A. 服従性", "B. 肥満症", "C. 障害物", "D. 観察力"], "B",
     ["A. obesity", "B. obedience", "C. obstacle", "D. observe"], "A",
     "Obesity is a growing health concern worldwide.（肥満は世界中で増大する健康問題だ。）",
     "Childhood obesity has increased significantly.（小児肥満は大幅に増加した。）"),
    ("hygiene", "háidʒiːn", "衛生", "A2",
     ["A. 衛生管理", "B. 水素結合", "C. 仮説内容", "D. 偽善行為"], "A",
     ["A. hydrogen", "B. hygiene", "C. hypnosis", "D. hypocrisy"], "B",
     "Good hygiene helps prevent disease.（良い衛生管理は病気の予防に役立つ。）",
     "Personal hygiene is very important.（個人の衛生は非常に重要だ。）"),
    ("vaccine", "højvæksíːn", "ワクチン", "A2",
     ["A. ワクチン", "B. 掃除機", "C. 休暇期間", "D. 空席状況"], "A",
     ["A. vaccine", "B. vacuum", "C. vacation", "D. vacant"], "A",
     "The flu vaccine is available every autumn.（インフルエンザワクチンは毎年秋に利用可能だ。）",
     "Scientists developed the vaccine rapidly.（科学者たちはワクチンを迅速に開発した。）"),
    ("medication", "mèdikéiʃən", "薬", "A2",
     ["A. 瞑想行為", "B. 仲介作業", "C. 薬の服用", "D. 変更手続"], "C",
     ["A. meditation", "B. medication", "C. mediation", "D. moderation"], "B",
     "Are you taking any medication?（何か薬を服用していますか？）",
     "This medication should be taken with food.（この薬は食事と一緒に服用すべきだ。）"),
    ("supplement", "sʌ́pləmənt", "補助食品", "A2",
     ["A. 補助食品", "B. 供給物資", "C. 支持基盤", "D. 抑制効果"], "A",
     ["A. supplement", "B. supplying", "C. supremacy", "D. supporter"], "A",
     "She takes vitamin supplements every day.（彼女は毎日ビタミン補助食品を摂取している。）",
     "Dietary supplements are widely available.（栄養補助食品は広く入手可能だ。）"),
    ("physician", "fizíʃən", "内科医", "B1",
     ["A. 物理学者", "B. 内科医師", "C. 技術者", "D. 薬剤師"], "B",
     ["A. physician", "B. physicist", "C. pharmacy", "D. physical"], "A",
     "You should see a physician regularly.（定期的に内科医の診察を受けるべきだ。）",
     "The physician recommended rest and fluids.（内科医は休息と水分補給を勧めた。）"),
    ("contagious", "kəntéidʒəs", "伝染する", "B1",
     ["A. 満足した", "B. 伝染する", "C. 隣接した", "D. 論争的な"], "B",
     ["A. contagious", "B. contiguous", "C. conscious", "D. consensus"], "A",
     "The common cold is highly contagious.（普通の風邪は非常に伝染しやすい。）",
     "Her enthusiasm is contagious.（彼女の熱意は伝染する。）"),
    ("rehabilitation", "rìːhəbìlitéiʃən", "リハビリ", "B1",
     ["A. リハビリ治療", "B. 信頼性確認", "C. 関係性構築", "D. 宗教的行事"], "A",
     ["A. rehabilitation", "B. relationship", "C. reliability", "D. registration"], "A",
     "He is undergoing rehabilitation after the accident.（彼は事故後にリハビリを受けている。）",
     "The rehabilitation program lasts three months.（リハビリプログラムは3ヶ月間続く。）"),
    # === Environment (15) ===
    ("sustainable", "səstéinəbl", "持続可能な", "B1",
     ["A. 持続可能な", "B. 実質的な", "C. 適切妥当な", "D. 耐久性ある"], "A",
     ["A. suitable", "B. substantial", "C. sustainable", "D. sufficient"], "C",
     "We need sustainable energy sources.（持続可能なエネルギー源が必要だ。）",
     "The company promotes sustainable development.（その会社は持続可能な開発を推進している。）"),
    ("pollution", "pəlúːʃən", "汚染", "A2",
     ["A. 解決策", "B. 人口数", "C. 汚染問題", "D. 位置情報"], "C",
     ["A. solution", "B. pollution", "C. position", "D. portion"], "B",
     "Air pollution is a serious problem in many cities.（大気汚染は多くの都市で深刻な問題だ。）",
     "We must reduce water pollution.（水質汚染を減らさなければならない。）"),
    ("conservation", "kɑ̀nsərvéiʃən", "保全", "B1",
     ["A. 会話活動", "B. 保全活動", "C. 建設工事", "D. 集中力"], "B",
     ["A. conversation", "B. conservation", "C. construction", "D. convention"], "B",
     "Wildlife conservation is important for biodiversity.（野生生物の保全は生物多様性にとって重要だ。）",
     "The park focuses on nature conservation.（その公園は自然保全に重点を置いている。）"),
    ("ecosystem", "íːkousìstəm", "生態系", "B1",
     ["A. 経済体制", "B. 反響効果", "C. 生態系統", "D. 教育制度"], "C",
     ["A. economic", "B. ecosystem", "C. echoing", "D. educator"], "B",
     "The coral reef ecosystem is in danger.（サンゴ礁の生態系は危険にさらされている。）",
     "Each ecosystem has its own unique balance.（各生態系には独自のバランスがある。）"),
    ("renewable", "rinjúːəbl", "再生可能な", "B1",
     ["A. 更新可能な", "B. 再生可能な", "C. 注目すべき", "D. 信頼できる"], "B",
     ["A. renewable", "B. removable", "C. remarkable", "D. reachable"], "A",
     "Solar power is a renewable energy source.（太陽光発電は再生可能なエネルギー源だ。）",
     "We should invest in renewable energy.（再生可能エネルギーに投資すべきだ。）"),
    ("emission", "imíʃən", "排出", "B1",
     ["A. 入場許可", "B. 排出物質", "C. 省略行為", "D. 感情表現"], "B",
     ["A. admission", "B. emission", "C. omission", "D. emotion"], "B",
     "The country aims to reduce carbon emissions.（その国は炭素排出量の削減を目指している。）",
     "Vehicle emissions contribute to air pollution.（車両の排出物は大気汚染の原因となる。）"),
    ("habitat", "hǽbitæt", "生息地", "B1",
     ["A. 習慣行為", "B. 居住区域", "C. 生息地域", "D. 道具装備"], "C",
     ["A. habitat", "B. inhabit", "C. exhibit", "D. prohibit"], "A",
     "The forest is the natural habitat of many species.（森はたくさんの種の自然の生息地だ。）",
     "Destruction of habitat threatens wildlife.（生息地の破壊は野生生物を脅かす。）"),
    ("recycle", "riːsáikl", "再利用する", "A2",
     ["A. 再利用する", "B. 回復する", "C. 再考する", "D. 再開する"], "A",
     ["A. recycle", "B. recover", "C. reclaim", "D. restore"], "A",
     "Please recycle paper and plastic.（紙とプラスチックを再利用してください。）",
     "We should recycle as much as possible.（できるだけ多く再利用すべきだ。）"),
    ("endangered", "indéindʒərd", "絶滅危惧の", "B1",
     ["A. 絶滅危惧の", "B. 怒りを感じる", "C. 勇気づけた", "D. 熱心に関与"], "A",
     ["A. encouraged", "B. endangered", "C. endurance", "D. engrossed"], "B",
     "The panda is an endangered species.（パンダは絶滅危惧種だ。）",
     "Many endangered animals need our protection.（多くの絶滅危惧動物は私たちの保護を必要としている。）"),
    ("erosion", "iróuʒən", "浸食", "B1",
     ["A. 爆発現象", "B. 浸食作用", "C. 感情表現", "D. 侵入行為"], "B",
     ["A. erosion", "B. eruption", "C. emotion", "D. invasion"], "A",
     "Soil erosion is caused by deforestation.（土壌浸食は森林伐採によって引き起こされる。）",
     "Coastal erosion is a serious environmental issue.（海岸浸食は深刻な環境問題だ。）"),
    ("extinction", "ikstíŋkʃən", "絶滅", "B1",
     ["A. 拡張行為", "B. 抽出作業", "C. 絶滅危機", "D. 存在意義"], "C",
     ["A. extension", "B. extraction", "C. extinction", "D. existence"], "C",
     "Many species face extinction due to human activity.（人間の活動のために多くの種が絶滅に直面している。）",
     "The extinction of dinosaurs occurred millions of years ago.（恐竜の絶滅は何百万年も前に起きた。）"),
    ("carbon", "kɑ́ːrbən", "炭素", "B1",
     ["A. 炭素元素", "B. 段ボール", "C. 炭水化物", "D. 車庫施設"], "A",
     ["A. carbon", "B. carton", "C. carpet", "D. cargo"], "A",
     "We need to reduce our carbon footprint.（炭素排出量を減らす必要がある。）",
     "Carbon dioxide levels are rising.（二酸化炭素の濃度が上昇している。）"),
    ("deforestation", "diːfɔ̀ːristéiʃən", "森林伐採", "B1",
     ["A. 森林伐採", "B. 脱水症状", "C. 変形加工", "D. 除染作業"], "A",
     ["A. deforestation", "B. dehydration", "C. deformation", "D. depreciation"], "A",
     "Deforestation destroys animal habitats.（森林伐採は動物の生息地を破壊する。）",
     "Illegal deforestation must be stopped.（違法な森林伐採は止めなければならない。）"),
    ("biodiversity", "bàioudaivə́ːrsəti", "生物多様性", "B1",
     ["A. 生物多様性", "B. 自伝内容", "C. 生化学反応", "D. 伝記文学"], "A",
     ["A. biography", "B. biochemistry", "C. biodiversity", "D. bibliography"], "C",
     "Protecting biodiversity is essential for the planet.（生物多様性の保護は地球にとって不可欠だ。）",
     "The island is known for its rich biodiversity.（その島は豊かな生物多様性で知られている。）"),
    ("compost", "kɑ́mpɔːst", "堆肥", "A2",
     ["A. 堆肥材料", "B. 構成要素", "C. 競争相手", "D. 作曲作品"], "A",
     ["A. compost", "B. compose", "C. compete", "D. compass"], "A",
     "We make compost from kitchen scraps.（台所の残飯から堆肥を作る。）",
     "Adding compost enriches the soil.（堆肥を加えると土壌が豊かになる。）"),
    # === Technology (14) ===
    ("algorithm", "ǽlgərìðəm", "アルゴリズム", "B1",
     ["A. アルゴリズム", "B. アレルギー反応", "C. 代数学分野", "D. 同盟関係"], "A",
     ["A. allergy", "B. algebra", "C. algorithm", "D. alliance"], "C",
     "The search engine uses a complex algorithm.（その検索エンジンは複雑なアルゴリズムを使用している。）",
     "This algorithm sorts data efficiently.（このアルゴリズムはデータを効率的に並べ替える。）"),
    ("database", "déitəbèis", "データベース", "A2",
     ["A. データベース", "B. 期限日", "C. 基本日付", "D. 議論題材"], "A",
     ["A. database", "B. deadline", "C. dateline", "D. debate"], "A",
     "All customer records are stored in the database.（全顧客記録はデータベースに保存されている。）",
     "We need to update the database regularly.（定期的にデータベースを更新する必要がある。）"),
    ("encryption", "inkrípʃən", "暗号化", "B1",
     ["A. 入学手続", "B. 暗号化処理", "C. 百科事典", "D. 碑文記録"], "B",
     ["A. enrollment", "B. encryption", "C. encounter", "D. endurance"], "B",
     "Encryption protects your personal data.（暗号化はあなたの個人データを保護する。）",
     "All messages use end-to-end encryption.（全メッセージはエンドツーエンド暗号化を使用している。）"),
    ("interface", "íntərfèis", "インターフェース", "B1",
     ["A. 干渉行為", "B. インターフェース", "C. 仲介役割", "D. 交差地点"], "B",
     ["A. interfere", "B. interface", "C. interpret", "D. interval"], "B",
     "The user interface is easy to navigate.（ユーザーインターフェースは操作しやすい。）",
     "We redesigned the software interface.（ソフトウェアのインターフェースを再設計した。）"),
    ("compatible", "kəmpǽtəbl", "互換性のある", "B1",
     ["A. 比較できる", "B. 互換性のある", "C. 有能である", "D. 快適である"], "B",
     ["A. comparable", "B. compatible", "C. competent", "D. compliant"], "B",
     "This software is compatible with Windows.（このソフトウェアはWindowsと互換性がある。）",
     "Make sure the devices are compatible.（デバイスに互換性があることを確認してください。）"),
    ("malware", "mǽlwɛər", "マルウェア", "B1",
     ["A. ハードウェア", "B. マルウェア", "C. ソフトウェア", "D. フリーウェア"], "B",
     ["A. hardware", "B. malware", "C. software", "D. firmware"], "B",
     "Malware can steal your personal information.（マルウェアは個人情報を盗むことがある。）",
     "Install antivirus software to protect against malware.（マルウェアから保護するためにウイルス対策ソフトを入れよう。）"),
    ("bandwidth", "bǽndwìdθ", "帯域幅", "B1",
     ["A. 帯域幅", "B. 包帯素材", "C. 手すり部分", "D. 腕輪装飾"], "A",
     ["A. bandwidth", "B. bandage", "C. banister", "D. bracelet"], "A",
     "Video streaming requires high bandwidth.（動画のストリーミングには高い帯域幅が必要だ。）",
     "The bandwidth of this connection is limited.（この接続の帯域幅は限られている。）"),
    ("server", "sə́ːrvər", "サーバー", "A2",
     ["A. サーバー", "B. 調査員", "C. 保管庫", "D. 上位者"], "A",
     ["A. server", "B. survey", "C. severe", "D. service"], "A",
     "The server is down for maintenance.（サーバーはメンテナンスのため停止中だ。）",
     "Data is stored on a remote server.（データはリモートサーバーに保存されている。）"),
    ("debug", "diːbʌ́g", "デバッグする", "B1",
     ["A. 拒否する", "B. 討論する", "C. デバッグする", "D. 控除する"], "C",
     ["A. debate", "B. debug", "C. deduct", "D. defeat"], "B",
     "It took hours to debug the program.（プログラムのデバッグに何時間もかかった。）",
     "We need to debug this code before release.（リリース前にこのコードをデバッグする必要がある。）"),
    ("pixel", "píksəl", "ピクセル", "A2",
     ["A. ピクセル", "B. 漬け物容器", "C. 操縦桿", "D. 枕カバー"], "A",
     ["A. pickle", "B. pistol", "C. pixel", "D. pillar"], "C",
     "Each pixel on the screen displays a color.（画面の各ピクセルは色を表示する。）",
     "This camera captures 20 million pixels.（このカメラは2000万ピクセルを撮影できる。）"),
    ("synchronize", "síŋkrənàiz", "同期する", "B1",
     ["A. 同情する", "B. 同期する", "C. 合成する", "D. 統合する"], "B",
     ["A. sympathize", "B. synchronize", "C. synthesize", "D. symbolize"], "B",
     "You can synchronize your data across devices.（デバイス間でデータを同期できる。）",
     "Please synchronize your calendar with the team.（チームとカレンダーを同期してください。）"),
    ("navigate", "nǽvigèit", "操作する", "A2",
     ["A. 交渉する", "B. 操作する", "C. 指名する", "D. 物語る"], "B",
     ["A. negotiate", "B. navigate", "C. nominate", "D. narrate"], "B",
     "The website is easy to navigate.（そのウェブサイトは操作しやすい。）",
     "Use the GPS to navigate to the destination.（目的地まで操作するのにGPSを使おう。）"),
    ("automate", "ɔ́ːtəmèit", "自動化する", "B1",
     ["A. 自動化する", "B. 認可する", "C. 集積する", "D. 指定する"], "A",
     ["A. automate", "B. authorize", "C. annotate", "D. alternate"], "A",
     "We want to automate repetitive tasks.（繰り返しの作業を自動化したい。）",
     "Many factories automate their production lines.（多くの工場が生産ラインを自動化している。）"),
    ("streaming", "stríːmiŋ", "ストリーミング", "A2",
     ["A. ストリーミング", "B. 強化行為", "C. 構造構築", "D. ストレッチ"], "A",
     ["A. streaming", "B. stretching", "C. steering", "D. striking"], "A",
     "Streaming services have changed how we watch movies.（ストリーミングサービスは映画の視聴方法を変えた。）",
     "Live streaming is popular on social media.（ライブストリーミングはSNSで人気がある。）"),
    # === Social/Emotions (14) ===
    ("empathy", "émpəθi", "共感", "B1",
     ["A. 空虚感", "B. 共感能力", "C. 緊急性", "D. 強調点"], "B",
     ["A. empathy", "B. apathy", "C. sympathy", "D. antipathy"], "A",
     "Empathy helps us understand others' feelings.（共感は他者の感情を理解するのに役立つ。）",
     "Show empathy toward people in need.（困っている人に共感を示そう。）"),
    ("prejudice", "prédʒudis", "偏見", "B1",
     ["A. 偏見差別", "B. 前置き文", "C. 予測結果", "D. 優先事項"], "A",
     ["A. prejudice", "B. preface", "C. predict", "D. precaution"], "A",
     "We must fight against racial prejudice.（人種的偏見と闘わなければならない。）",
     "Prejudice can lead to discrimination.（偏見は差別につながりうる。）"),
    ("tolerance", "tɑ́lərəns", "寛容", "B1",
     ["A. 寛容さ", "B. 才能力", "C. 通行料", "D. 拷問行為"], "A",
     ["A. tolerance", "B. talent", "C. turbulence", "D. tendency"], "A",
     "Society needs more tolerance for diversity.（社会にはより多くの多様性への寛容が必要だ。）",
     "Religious tolerance is important in modern society.（宗教的寛容は現代社会で重要だ。）"),
    ("dignity", "dígnəti", "尊厳", "B1",
     ["A. 尊厳意識", "B. 勤勉さ", "C. 数字表示", "D. 消化作用"], "A",
     ["A. dignity", "B. divinity", "C. dynasty", "D. diligent"], "A",
     "Every person deserves to be treated with dignity.（すべての人は尊厳を持って扱われるべきだ。）",
     "She maintained her dignity throughout the ordeal.（彼女は試練を通じて尊厳を保った。）"),
    ("discrimination", "diskrìmənéiʃən", "差別", "B1",
     ["A. 差別行為", "B. 配分作業", "C. 中断結果", "D. 不満表明"], "A",
     ["A. distribution", "B. discrimination", "C. disconnection", "D. disagreement"], "B",
     "Discrimination based on gender is illegal.（性別に基づく差別は違法だ。）",
     "We must stand against all forms of discrimination.（あらゆる形態の差別に立ち向かわなければならない。）"),
    ("stereotype", "stériətàip", "固定観念", "B1",
     ["A. 立体音響", "B. 固定観念", "C. 殺菌処理", "D. 蓄音装置"], "B",
     ["A. sterile", "B. stereotype", "C. stimulate", "D. structure"], "B",
     "We should avoid cultural stereotypes.（文化的な固定観念を避けるべきだ。）",
     "Don't believe every stereotype you hear.（聞いた固定観念をすべて信じてはいけない。）"),
    ("compassion", "kəmpǽʃən", "思いやり", "B1",
     ["A. 競争意識", "B. 思いやり", "C. 賠償請求", "D. 構成要素"], "B",
     ["A. companion", "B. compassion", "C. comparison", "D. complaint"], "B",
     "She showed great compassion for the victims.（彼女は被害者に大きな思いやりを示した。）",
     "Compassion is the foundation of kindness.（思いやりは優しさの土台だ。）"),
    ("isolation", "àisəléiʃən", "孤立", "B1",
     ["A. 孤立状態", "B. 刺激効果", "C. 例示説明", "D. 設置作業"], "A",
     ["A. isolation", "B. illustration", "C. installation", "D. irritation"], "A",
     "Social isolation can affect mental health.（社会的孤立は精神的健康に影響を与えうる。）",
     "The village suffered from isolation during winter.（その村は冬の間、孤立に苦しんだ。）"),
    ("grief", "griːf", "悲嘆", "B1",
     ["A. 把握力", "B. 貪欲さ", "C. 悲嘆感情", "D. 優雅さ"], "C",
     ["A. grief", "B. greed", "C. grace", "D. grasp"], "A",
     "She was overcome with grief after the loss.（喪失の後、彼女は悲嘆に暮れた。）",
     "Time helps heal grief.（時間が悲嘆を癒すのに役立つ。）"),
    ("envy", "énvi", "嫉妬", "A2",
     ["A. 嫉妬感情", "B. 精力増加", "C. 封筒素材", "D. 環境要因"], "A",
     ["A. envy", "B. energy", "C. entry", "D. enemy"], "A",
     "His success filled her with envy.（彼の成功は彼女を嫉妬で満たした。）",
     "Don't let envy control your actions.（嫉妬に行動を支配させてはいけない。）"),
    ("resentment", "rizéntmənt", "憤り", "B1",
     ["A. 復活効果", "B. 類似点", "C. 憤りの気持", "D. 退職金"], "C",
     ["A. retirement", "B. resentment", "C. resemblance", "D. restraint"], "B",
     "He felt deep resentment toward his former boss.（彼は元上司に深い憤りを感じた。）",
     "Holding onto resentment is unhealthy.（憤りを抱え続けることは不健康だ。）"),
    ("hostility", "hɑstíləti", "敵意", "B1",
     ["A. 歓待精神", "B. 人質状態", "C. 敵意感情", "D. 正直さ"], "C",
     ["A. hospitality", "B. hostility", "C. hostage", "D. honesty"], "B",
     "There was hostility between the two groups.（二つのグループの間に敵意があった。）",
     "His hostility made everyone uncomfortable.（彼の敵意は皆を不快にさせた。）"),
    ("nostalgia", "nɑstǽldʒə", "懐かしさ", "B1",
     ["A. 懐かしさ", "B. 神経痛", "C. 不安感", "D. 無関心"], "A",
     ["A. neuralgia", "B. nostalgia", "C. negligence", "D. narrative"], "B",
     "The old photos filled her with nostalgia.（古い写真は彼女を懐かしさで満たした。）",
     "He felt nostalgia for his childhood days.（彼は子供時代への懐かしさを感じた。）"),
    ("morale", "mərǽl", "士気", "B1",
     ["A. 道徳観念", "B. 士気状態", "C. 記念碑", "D. 死亡率"], "B",
     ["A. moral", "B. morale", "C. mortal", "D. morbid"], "B",
     "Team morale is high after the victory.（勝利の後、チームの士気は高い。）",
     "Good leadership boosts employee morale.（良いリーダーシップは従業員の士気を高める。）"),
    # === Travel/Culture (12) ===
    ("itinerary", "aitínərèri", "旅程", "B1",
     ["A. 旅程計画", "B. 在庫品目", "C. 繰り返し", "D. 灌漑設備"], "A",
     ["A. itinerary", "B. inventory", "C. iteration", "D. irrigation"], "A",
     "Please check your travel itinerary.（旅程を確認してください。）",
     "The tour itinerary includes five cities.（ツアーの旅程は5つの都市を含んでいる。）"),
    ("monument", "mɑ́njumənt", "記念碑", "A2",
     ["A. 記念碑建造物", "B. 一瞬の出来事", "C. 修道院施設", "D. 怪物的存在"], "A",
     ["A. moment", "B. monster", "C. monument", "D. monetary"], "C",
     "The monument was built to honor war heroes.（その記念碑は戦争の英雄をたたえるために建てられた。）",
     "We visited the historical monument.（歴史的な記念碑を訪れた。）"),
    ("heritage", "héritidʒ", "遺産", "B1",
     ["A. 遺産文化", "B. 英雄行為", "C. 異端思想", "D. 密閉容器"], "A",
     ["A. heritage", "B. heroism", "C. heretic", "D. hermetic"], "A",
     "Kyoto is famous for its cultural heritage.（京都は文化遺産で有名だ。）",
     "We should protect our natural heritage.（自然遺産を守るべきだ。）"),
    ("authentic", "ɔːθéntik", "本物の", "B1",
     ["A. 自動的な", "B. 本物の", "C. 権威的な", "D. 独裁的な"], "B",
     ["A. automatic", "B. authentic", "C. authority", "D. autonomy"], "B",
     "This restaurant serves authentic Japanese food.（このレストランは本物の日本料理を出す。）",
     "Is this painting authentic?（この絵画は本物ですか？）"),
    ("cuisine", "kwizíːn", "料理", "A2",
     ["A. 従兄弟", "B. 料理法", "C. 衣装類", "D. 手がかり"], "B",
     ["A. cousin", "B. cuisine", "C. costume", "D. cushion"], "B",
     "Japanese cuisine is popular worldwide.（日本料理は世界中で人気がある。）",
     "I enjoy trying different types of cuisine.（いろいろな種類の料理を試すのが好きだ。）"),
    ("excursion", "ikskə́ːrʒən", "小旅行", "A2",
     ["A. 言い訳", "B. 小旅行", "C. 除外処理", "D. 排出物質"], "B",
     ["A. excursion", "B. exclusion", "C. execution", "D. exhaustion"], "A",
     "We went on a day excursion to the mountains.（山への日帰り小旅行に出かけた。）",
     "The school organized an excursion to the museum.（学校が博物館への小旅行を企画した。）"),
    ("expedition", "èkspədíʃən", "探検", "B1",
     ["A. 期待感情", "B. 探検活動", "C. 経費支出", "D. 体験学習"], "B",
     ["A. expectation", "B. expedition", "C. expenditure", "D. experience"], "B",
     "The expedition to the Arctic lasted three months.（北極への探検は3ヶ月間続いた。）",
     "They planned an expedition to the jungle.（彼らはジャングルへの探検を計画した。）"),
    ("landmark", "lǽndmɑːrk", "名所", "A2",
     ["A. 名所旧跡", "B. 地主階級", "C. 景観設計", "D. 着陸地点"], "A",
     ["A. landlord", "B. landscape", "C. landmark", "D. landslide"], "C",
     "Tokyo Tower is a famous landmark.（東京タワーは有名な名所だ。）",
     "The guidebook lists all the major landmarks.（ガイドブックにはすべての主要な名所が載っている。）"),
    ("pilgrim", "pílgrim", "巡礼者", "B1",
     ["A. 巡礼者", "B. 柱型構造", "C. 略奪者", "D. 操縦者"], "A",
     ["A. pilgrim", "B. pillar", "C. pirate", "D. pioneer"], "A",
     "Many pilgrims visit Shikoku each year.（毎年多くの巡礼者が四国を訪れる。）",
     "The pilgrim walked for 88 days.（その巡礼者は88日間歩いた。）"),
    ("indigenous", "indídʒənəs", "先住の", "B1",
     ["A. 無関心な", "B. 先住民の", "C. 独立した", "D. 勤勉な"], "B",
     ["A. indifferent", "B. indigenous", "C. individual", "D. industrial"], "B",
     "Indigenous cultures deserve respect and protection.（先住民の文化は尊重と保護に値する。）",
     "The museum exhibits indigenous art.（その博物館は先住民の芸術を展示している。）"),
    ("sojourn", "sóudʒəːrn", "滞在", "B1",
     ["A. 滞在期間", "B. 旅行日誌", "C. 出発準備", "D. 帰還作業"], "A",
     ["A. sojourn", "B. journal", "C. journey", "D. adjourn"], "A",
     "Her sojourn in Paris lasted two years.（彼女のパリでの滞在は2年間続いた。）",
     "We enjoyed our brief sojourn in the countryside.（田舎での短い滞在を楽しんだ。）"),
    ("dialect", "dáiəlèkt", "方言", "A2",
     ["A. 方言地域語", "B. 対話交流", "C. 直径長さ", "D. 図表表示"], "A",
     ["A. dialect", "B. dialogue", "C. diameter", "D. diagonal"], "A",
     "Each region has its own dialect.（各地域には独自の方言がある。）",
     "The Osaka dialect is well known in Japan.（大阪方言は日本でよく知られている。）"),
    # === Daily Life (12) ===
    ("errand", "érənd", "用事", "A2",
     ["A. 用事仕事", "B. 誤り間違", "C. 到着予定", "D. 手配調整"], "A",
     ["A. errand", "B. errant", "C. error", "D. arrest"], "A",
     "I have to run some errands this afternoon.（今日の午後いくつかの用事を済ませなければならない。）",
     "She went out on an errand.（彼女は用事で外出した。）"),
    ("chore", "tʃɔːr", "雑用", "A2",
     ["A. 合唱歌曲", "B. 雑用作業", "C. 和音構造", "D. 中核部分"], "B",
     ["A. chord", "B. chore", "C. chorus", "D. chart"], "B",
     "Doing household chores is everyone's responsibility.（家事の雑用はみんなの責任だ。）",
     "He dislikes doing chores on weekends.（彼は週末に雑用をするのが嫌いだ。）"),
    ("clutter", "klʌ́tər", "散らかり", "A2",
     ["A. 集合体", "B. 散らかり", "C. 覆い布", "D. 群集感"], "B",
     ["A. cluster", "B. clutter", "C. clatter", "D. closure"], "B",
     "There is too much clutter in this room.（この部屋は散らかりすぎている。）",
     "Let's clear the clutter from the desk.（机の上の散らかりを片付けよう。）"),
    ("appliance", "əpláiəns", "家電製品", "A2",
     ["A. 応募書類", "B. 拍手喝采", "C. 家電製品", "D. 外見容姿"], "C",
     ["A. appliance", "B. alliance", "C. ambulance", "D. allowance"], "A",
     "We bought new kitchen appliances.（新しいキッチン家電製品を買った。）",
     "This appliance saves a lot of energy.（この家電製品はたくさんのエネルギーを節約する。）"),
    ("utensil", "juːténsəl", "器具", "A2",
     ["A. 器具道具", "B. 有用性", "C. 発言内容", "D. 制服一式"], "A",
     ["A. utensil", "B. utility", "C. unusual", "D. uniform"], "A",
     "Cooking utensils are in the drawer.（調理器具は引き出しの中にある。）",
     "Please wash the utensils after use.（使用後は器具を洗ってください。）"),
    ("stain", "stéin", "汚れ", "A2",
     ["A. 汚れ付着", "B. 染色加工", "C. 階段構造", "D. 主要部分"], "A",
     ["A. stain", "B. stair", "C. stake", "D. stage"], "A",
     "I can't remove this coffee stain.（このコーヒーの汚れが落とせない。）",
     "There is a stain on your shirt.（シャツに汚れがついている。）"),
    ("leak", "liːk", "漏れ", "A2",
     ["A. 漏れ現象", "B. 葉っぱ", "C. 跳躍動作", "D. 繋がり"], "A",
     ["A. leak", "B. leaf", "C. leap", "D. lead"], "A",
     "There is a water leak in the bathroom.（浴室で水漏れがある。）",
     "The roof has a leak.（屋根に漏れがある。）"),
    ("plumber", "plʌ́mər", "配管工", "A2",
     ["A. 大工職人", "B. 配管工人", "C. 農業従事", "D. 画家芸術"], "B",
     ["A. plumber", "B. planner", "C. painter", "D. pioneer"], "A",
     "We called a plumber to fix the pipe.（パイプを直すために配管工を呼んだ。）",
     "The plumber repaired the broken faucet.（配管工が壊れた蛇口を修理した。）"),
    ("renovation", "rènəvéiʃən", "改装", "B1",
     ["A. 改装工事", "B. 革新発明", "C. 更新手続", "D. 予約確認"], "A",
     ["A. renovation", "B. innovation", "C. reservation", "D. revelation"], "A",
     "The house needs major renovation.（その家は大規模な改装が必要だ。）",
     "The renovation of the building took six months.（建物の改装に6ヶ月かかった。）"),
    ("mortgage", "mɔ́ːrgidʒ", "住宅ローン", "B1",
     ["A. 住宅ローン", "B. 死亡率統計", "C. 抵当権設定", "D. 動機付け"], "A",
     ["A. mortgage", "B. mortality", "C. moreover", "D. motivate"], "A",
     "They are paying off their mortgage.（彼らは住宅ローンを返済中だ。）",
     "The mortgage rate has increased this year.（今年、住宅ローン金利が上がった。）"),
    ("tenant", "ténənt", "入居者", "B1",
     ["A. 入居者", "B. 傾向性", "C. 内容物", "D. 意図目的"], "A",
     ["A. tenant", "B. tender", "C. tension", "D. terrain"], "A",
     "The tenant pays rent every month.（入居者は毎月家賃を払う。）",
     "New tenants moved in last week.（先週、新しい入居者が引っ越してきた。）"),
    ("commuter", "kəmjúːtər", "通勤者", "A2",
     ["A. 通勤者", "B. 電算機", "C. 競争者", "D. 解説者"], "A",
     ["A. commuter", "B. computer", "C. consumer", "D. composer"], "A",
     "Many commuters take the train to work.（多くの通勤者は電車で通勤する。）",
     "The commuter train was delayed this morning.（通勤電車は今朝遅れた。）"),
    # === Legal/Formal (12) ===
    ("legislation", "lèdʒisléiʃən", "法律", "B1",
     ["A. 正当化行為", "B. 法律制定", "C. 伝説物語", "D. 資格認定"], "B",
     ["A. legitimate", "B. legislation", "C. legendary", "D. liberation"], "B",
     "New legislation was passed to protect the environment.（環境を保護する新しい法律が可決された。）",
     "The government proposed new legislation.（政府は新しい法律を提案した。）"),
    ("verdict", "və́ːrdikt", "評決", "B1",
     ["A. 検証結果", "B. 動詞変化", "C. 評決内容", "D. 美徳概念"], "C",
     ["A. verdict", "B. verbose", "C. version", "D. vertical"], "A",
     "The jury reached a verdict of not guilty.（陪審員は無罪の評決に達した。）",
     "Everyone waited anxiously for the verdict.（皆が不安げに評決を待った。）"),
    ("testimony", "téstəmòuni", "証言", "B1",
     ["A. 領土領域", "B. 証言内容", "C. 遺言書類", "D. 一時的な"], "B",
     ["A. territory", "B. testimony", "C. testament", "D. temporary"], "B",
     "Her testimony helped solve the case.（彼女の証言が事件の解決に役立った。）",
     "The witness gave important testimony.（証人は重要な証言をした。）"),
    ("attorney", "ətə́ːrni", "弁護士", "B1",
     ["A. 注意事項", "B. 弁護士", "C. 出席者", "D. 達成者"], "B",
     ["A. attorney", "B. attendee", "C. attainer", "D. attaché"], "A",
     "You should consult an attorney before signing.（署名する前に弁護士に相談すべきだ。）",
     "The attorney represented the defendant.（弁護士が被告を弁護した。）"),
    ("plaintiff", "pléintif", "原告", "B1",
     ["A. 原告側", "B. 平原地帯", "C. 苦情内容", "D. 惑星天体"], "A",
     ["A. plaintiff", "B. platform", "C. platitude", "D. pleasure"], "A",
     "The plaintiff filed a lawsuit against the company.（原告は会社に対して訴訟を起こした。）",
     "The plaintiff's lawyer presented the evidence.（原告の弁護士が証拠を提示した。）"),
    ("jurisdiction", "dʒùərisdíkʃən", "管轄", "B1",
     ["A. 正当化根拠", "B. 管轄権限", "C. 陪審選出", "D. 裁判判決"], "B",
     ["A. justification", "B. jurisdiction", "C. juxtapose", "D. jubilation"], "B",
     "This matter falls outside our jurisdiction.（この問題は我々の管轄外だ。）",
     "The court has jurisdiction over this area.（裁判所はこの地域に管轄権を持つ。）"),
    ("statute", "stǽtʃuːt", "法令", "B1",
     ["A. 像彫刻", "B. 地位身分", "C. 法令条文", "D. 声明発表"], "C",
     ["A. statue", "B. status", "C. statute", "D. stature"], "C",
     "The statute was enacted in 2020.（その法令は2020年に制定された。）",
     "This act violates the statute.（この行為は法令に違反する。）"),
    ("amendment", "əméndmənt", "修正", "B1",
     ["A. 娯楽活動", "B. 修正変更", "C. 達成業績", "D. 宣告発表"], "B",
     ["A. amusement", "B. amendment", "C. amazement", "D. assessment"], "B",
     "The amendment to the law was approved.（法律の修正が承認された。）",
     "They proposed an amendment to the contract.（彼らは契約の修正を提案した。）"),
    ("petition", "pətíʃən", "請願", "B1",
     ["A. 分割処理", "B. 請願書類", "C. 競争試合", "D. 許可認可"], "B",
     ["A. partition", "B. petition", "C. physician", "D. permission"], "B",
     "They signed a petition to save the park.（彼らは公園を救うための請願に署名した。）",
     "The petition received thousands of signatures.（その請願は何千もの署名を集めた。）"),
    ("arbitration", "ɑ̀ːrbitréiʃən", "仲裁", "B1",
     ["A. 仲裁手続", "B. 吸収作用", "C. 加速運動", "D. 適応変化"], "A",
     ["A. arbitration", "B. absorption", "C. acceleration", "D. aspiration"], "A",
     "The dispute was settled through arbitration.（紛争は仲裁を通じて解決された。）",
     "Both parties agreed to arbitration.（両当事者が仲裁に同意した。）"),
    ("compliance", "kəmpláiəns", "法令遵守", "B1",
     ["A. 法令遵守", "B. 苦情処理", "C. 完了通知", "D. 複雑問題"], "A",
     ["A. compliance", "B. complaint", "C. competence", "D. component"], "A",
     "The company is in full compliance with regulations.（その会社は規制を完全に遵守している。）",
     "Compliance with safety rules is mandatory.（安全規則の遵守は義務だ。）"),
    ("prosecution", "prɑ̀sikjúːʃən", "起訴", "B1",
     ["A. 保護活動", "B. 起訴手続", "C. 生産工程", "D. 進歩発展"], "B",
     ["A. protection", "B. prosecution", "C. production", "D. progression"], "B",
     "The prosecution presented strong evidence.（検察側は強力な証拠を提示した。）",
     "He faces prosecution for fraud.（彼は詐欺で起訴に直面している。）"),
    # === Science (14) ===
    ("molecule", "mɑ́ləkjùːl", "分子", "B1",
     ["A. 分子構造", "B. 単一文化", "C. 記念日", "D. 独占権"], "A",
     ["A. molecule", "B. monocle", "C. monument", "D. monopoly"], "A",
     "A water molecule consists of hydrogen and oxygen.（水分子は水素と酸素で構成されている。）",
     "Scientists studied the structure of the molecule.（科学者たちは分子の構造を研究した。）"),
    ("gravity", "grǽvəti", "重力", "A2",
     ["A. 墓地施設", "B. 重力引力", "C. 砂利道路", "D. 感謝気持"], "B",
     ["A. gravity", "B. gravel", "C. gratitude", "D. graceful"], "A",
     "Gravity keeps us on the ground.（重力が私たちを地面に留めている。）",
     "Newton discovered the law of gravity.（ニュートンは重力の法則を発見した。）"),
    ("evolution", "èvəlúːʃən", "進化", "B1",
     ["A. 評価結果", "B. 進化過程", "C. 革命運動", "D. 排除行為"], "B",
     ["A. evaluation", "B. evolution", "C. revolution", "D. exclusion"], "B",
     "The theory of evolution explains biodiversity.（進化論は生物多様性を説明する。）",
     "Technology evolution has been rapid.（技術の進化は急速だった。）"),
    ("experiment", "ikspérəmənt", "実験", "A2",
     ["A. 体験活動", "B. 実験調査", "C. 期待感情", "D. 説明文章"], "B",
     ["A. experience", "B. experiment", "C. expedition", "D. expression"], "B",
     "The experiment produced surprising results.（その実験は驚くべき結果を生み出した。）",
     "We conducted an experiment in the lab.（研究室で実験を実施した。）"),
    ("specimen", "spésəmən", "標本", "B1",
     ["A. 標本試料", "B. 観客席", "C. 推測推理", "D. 専門分野"], "A",
     ["A. specimen", "B. spectator", "C. spectrum", "D. specific"], "A",
     "The museum has many rare specimens.（その博物館には多くの珍しい標本がある。）",
     "Please provide a blood specimen for testing.（検査のために血液標本を提供してください。）"),
    ("organism", "ɔ́ːrgənìzəm", "生物", "B1",
     ["A. 生物個体", "B. 組織団体", "C. 臓器器官", "D. 有機栽培"], "A",
     ["A. organism", "B. organize", "C. organic", "D. orchestra"], "A",
     "Every living organism needs water.（すべての生物は水を必要としている。）",
     "This organism can survive in extreme heat.（この生物は極度の暑さの中でも生き残れる。）"),
    ("nucleus", "njúːkliəs", "核", "B1",
     ["A. 核の構造", "B. 原子力発電", "C. 数値計算", "D. 看護業務"], "A",
     ["A. nucleus", "B. nuclear", "C. neutral", "D. numeral"], "A",
     "The nucleus contains the cell's DNA.（核は細胞のDNAを含んでいる。）",
     "Protons are found in the nucleus of an atom.（陽子は原子の核の中に見つかる。）"),
    ("compound", "kɑ́mpaund", "化合物", "B1",
     ["A. 化合物質", "B. 不満苦情", "C. 仲間同士", "D. 比較対照"], "A",
     ["A. compound", "B. complaint", "C. companion", "D. component"], "A",
     "Water is a chemical compound.（水は化学化合物だ。）",
     "This compound is made of two elements.（この化合物は2つの元素でできている。）"),
    ("velocity", "vəlɑ́siti", "速度", "B1",
     ["A. 速度表記", "B. 都市開発", "C. 検証結果", "D. 多様性"], "A",
     ["A. velocity", "B. vicinity", "C. validity", "D. variety"], "A",
     "The velocity of light is extremely fast.（光の速度は極めて速い。）",
     "Wind velocity increased during the storm.（嵐の間に風速が増加した。）"),
    ("fossil", "fɑ́sl", "化石", "A2",
     ["A. 化石標本", "B. 祭り行事", "C. 養育里親", "D. 城塞施設"], "A",
     ["A. fossil", "B. festival", "C. foster", "D. fortress"], "A",
     "Dinosaur fossils were found in the desert.（恐竜の化石が砂漠で発見された。）",
     "This fossil is millions of years old.（この化石は何百万年も前のものだ。）"),
    ("microscope", "máikrəskòup", "顕微鏡", "A2",
     ["A. 顕微鏡", "B. 電子レンジ", "C. マイク装置", "D. 小型チップ"], "A",
     ["A. microphone", "B. microscope", "C. microchip", "D. microwave"], "B",
     "We used a microscope to observe the cells.（細胞を観察するために顕微鏡を使った。）",
     "The microscope revealed tiny organisms.（顕微鏡は微小な生物を映し出した。）"),
    ("laboratory", "lǽbərətɔ̀ːri", "研究室", "A2",
     ["A. 研究室施設", "B. 労働組合", "C. 迷宮構造", "D. 図書館業務"], "A",
     ["A. laboratory", "B. laborious", "C. labyrinth", "D. liberation"], "A",
     "The scientists work in a laboratory.（科学者たちは研究室で働いている。）",
     "The laboratory was well equipped.（その研究室は設備が整っていた。）"),
    ("catalyst", "kǽtəlɪst", "触媒", "B1",
     ["A. 触媒作用", "B. 目録一覧", "C. 大惨事", "D. 大聖堂"], "A",
     ["A. catalyst", "B. catalog", "C. catastrophe", "D. cathedral"], "A",
     "The enzyme acts as a catalyst.（その酵素は触媒として機能する。）",
     "Education can be a catalyst for change.（教育は変化の触媒になりうる。）"),
    ("photosynthesis", "fòutousínθəsis", "光合成", "B1",
     ["A. 光合成反応", "B. 写真撮影", "C. 哲学思想", "D. 音声合成"], "A",
     ["A. photography", "B. photosynthesis", "C. philosophy", "D. phonetics"], "B",
     "Plants produce energy through photosynthesis.（植物は光合成を通じてエネルギーを生産する。）",
     "Photosynthesis requires sunlight and water.（光合成には太陽光と水が必要だ。）"),
    # === Additional misc words to reach 250 ===
    ("abundant", "əbʌ́ndənt", "豊富な", "A2",
     ["A. 不足した", "B. 豊富な", "C. 適切な", "D. 曖昧な"], "B",
     ["A. absent", "B. abundant", "C. abstract", "D. absolute"], "B",
     "Japan has abundant natural beauty.（日本には豊かな自然美がある。）",
     "There is abundant evidence to support this theory.（この理論を支持する豊富な証拠がある。）"),
    ("acquire", "əkwáiər", "取得する", "B1",
     ["A. 同意する", "B. 取得する", "C. 要求する", "D. 質問する"], "B",
     ["A. acquire", "B. require", "C. inquire", "D. admire"], "A",
     "She acquired a new skill through training.（彼女は訓練を通じて新しいスキルを取得した。）",
     "The company plans to acquire a smaller firm.（その会社はより小さな会社を取得する予定だ。）"),
    ("adequate", "ǽdikwət", "十分な", "B1",
     ["A. 十分な量", "B. 適応した", "C. 隣接した", "D. 不適切な"], "A",
     ["A. adequate", "B. accurate", "C. adjacent", "D. advocate"], "A",
     "We have adequate supplies for the trip.（旅行に十分な物資がある。）",
     "The salary is adequate for our needs.（その給与は我々のニーズに十分だ。）"),
    ("adjacent", "ədʒéisənt", "隣接した", "B1",
     ["A. 調整した", "B. 隣接した", "C. 十分な", "D. 顕著な"], "B",
     ["A. adjusted", "B. adjacent", "C. adequate", "D. advanced"], "B",
     "The park is adjacent to the school.（公園は学校に隣接している。）",
     "Our room was adjacent to the elevator.（私たちの部屋はエレベーターに隣接していた。）"),
    ("anticipate", "æntísəpèit", "予想する", "B1",
     ["A. 予想する", "B. 参加する", "C. 感謝する", "D. 鑑定する"], "A",
     ["A. anticipate", "B. articulate", "C. appreciate", "D. approximate"], "A",
     "We anticipate a busy holiday season.（忙しい休暇シーズンを予想している。）",
     "I didn't anticipate such a warm welcome.（こんなに温かい歓迎を予想しなかった。）"),
    ("behalf", "bihǽf", "代わりに", "B1",
     ["A. 半分の量", "B. 行動様式", "C. 代わり代理", "D. 信念思想"], "C",
     ["A. behalf", "B. behave", "C. behind", "D. believe"], "A",
     "I am speaking on behalf of the team.（チームを代表して話しています。）",
     "She signed the contract on behalf of the company.（彼女は会社の代わりに契約に署名した。）"),
    ("burden", "bə́ːrdn", "負担", "B1",
     ["A. 負担重荷", "B. 国境線", "C. 退屈感情", "D. 埋葬行為"], "A",
     ["A. burden", "B. border", "C. boredom", "D. burial"], "A",
     "The tax burden is increasing.（税負担が増加している。）",
     "I don't want to be a burden on my family.（家族の負担になりたくない。）"),
    ("capacity", "kəpǽsəti", "能力", "B1",
     ["A. 首都機能", "B. 能力容量", "C. 捕獲行為", "D. 注意深さ"], "B",
     ["A. capacity", "B. capital", "C. captain", "D. capture"], "A",
     "The stadium has a capacity of 50,000.（そのスタジアムは5万人の収容能力がある。）",
     "She has the capacity to lead the team.（彼女にはチームを率いる能力がある。）"),
    ("cease", "siːs", "やめる", "B1",
     ["A. やめる停止", "B. 握り掴む", "C. 選択する", "D. 追いかける"], "A",
     ["A. seize", "B. cease", "C. chase", "D. chose"], "B",
     "The factory will cease production next month.（工場は来月生産をやめる。）",
     "Please cease making noise.（騒音を出すのをやめてください。）"),
    ("circumstance", "sə́ːrkəmstæns", "状況", "B1",
     ["A. 円周距離", "B. 状況事情", "C. 市民権利", "D. 回路設計"], "B",
     ["A. circumference", "B. circumstance", "C. circulation", "D. citizenship"], "B",
     "Under the circumstances, we had no choice.（その状況下では選択肢がなかった。）",
     "The circumstances of the accident are unclear.（事故の状況は不明だ。）"),
    ("civilization", "sìvələzéiʃən", "文明", "A2",
     ["A. 市民社会", "B. 文明社会", "C. 認定制度", "D. 祝典行事"], "B",
     ["A. civilization", "B. celebration", "C. circulation", "D. cultivation"], "A",
     "Ancient Greek civilization influenced the world.（古代ギリシャ文明は世界に影響を与えた。）",
     "Modern civilization depends on technology.（現代文明はテクノロジーに依存している。）"),
    ("coherent", "kouhíːrənt", "首尾一貫した", "B1",
     ["A. 首尾一貫した", "B. 一致した", "C. 競争的な", "D. 能力のある"], "A",
     ["A. coherent", "B. coincident", "C. competent", "D. confident"], "A",
     "His argument was clear and coherent.（彼の議論は明確で首尾一貫していた。）",
     "Please write a coherent essay.（首尾一貫したエッセイを書いてください。）"),
    ("commodity", "kəmɑ́dəti", "商品", "B1",
     ["A. 商品物資", "B. 日用品", "C. 共同体", "D. 快適さ"], "A",
     ["A. commodity", "B. community", "C. committee", "D. commuter"], "A",
     "Oil is an important commodity.（石油は重要な商品だ。）",
     "The price of this commodity has risen sharply.（この商品の価格は急激に上昇した。）"),
    ("comprehensive", "kɑ̀mprihénsiv", "包括的な", "B1",
     ["A. 包括的な", "B. 理解力の", "C. 競争的な", "D. 思いやりの"], "A",
     ["A. comprehensive", "B. comprehensible", "C. competitive", "D. compassionate"], "A",
     "The report provides a comprehensive overview.（その報告書は包括的な概要を提供する。）",
     "We need a comprehensive plan.（包括的な計画が必要だ。）"),
    ("conceal", "kənsíːl", "隠す", "B1",
     ["A. 承諾する", "B. 集中する", "C. 隠す秘匿", "D. 想像する"], "C",
     ["A. conceal", "B. concede", "C. conceive", "D. concern"], "A",
     "He tried to conceal the truth.（彼は真実を隠そうとした。）",
     "She could not conceal her excitement.（彼女は興奮を隠せなかった。）"),
    ("controversy", "kɑ́ntrəvə̀ːrsi", "論争", "B1",
     ["A. 論争問題", "B. 矛盾箇所", "C. 便利さ", "D. 会話交流"], "A",
     ["A. controversy", "B. contradiction", "C. convention", "D. convenience"], "A",
     "The decision caused a lot of controversy.（その決定は多くの論争を引き起こした。）",
     "The new policy sparked controversy.（新しい政策が論争を引き起こした。）"),
    ("convert", "kənvə́ːrt", "変換する", "B1",
     ["A. 運ぶ移す", "B. 会話する", "C. 変換する", "D. 確信する"], "C",
     ["A. convert", "B. convene", "C. convey", "D. converse"], "A",
     "You can convert dollars to yen at the bank.（銀行でドルを円に変換できる。）",
     "The building was converted into a hotel.（その建物はホテルに変換された。）"),
    ("cope", "kóup", "対処する", "A2",
     ["A. 対処する", "B. 写す複製", "C. 核の部分", "D. 覆う帽子"], "A",
     ["A. cope", "B. copy", "C. core", "D. cape"], "A",
     "She learned to cope with stress.（彼女はストレスに対処することを学んだ。）",
     "How do you cope with the heat?（暑さにどう対処していますか？）"),
    ("crucial", "krúːʃəl", "極めて重要な", "B1",
     ["A. 残酷な行為", "B. 極めて重要な", "C. 大雑把な", "D. 十字形の"], "B",
     ["A. crucial", "B. crystal", "C. chronic", "D. crossed"], "A",
     "This is a crucial decision for the company.（これは会社にとって極めて重要な決定だ。）",
     "Timing is crucial in business.（ビジネスではタイミングが極めて重要だ。）"),
    ("decade", "dékeid", "10年間", "A2",
     ["A. 10年間", "B. 衰退期", "C. 12月度", "D. 装飾品"], "A",
     ["A. decade", "B. decay", "C. decor", "D. defeat"], "A",
     "The city has changed a lot over the past decade.（過去10年間でその都市は大きく変わった。）",
     "She lived abroad for a decade.（彼女は10年間海外に住んだ。）"),
    ("declare", "dikléər", "宣言する", "B1",
     ["A. 減少する", "B. 宣言する", "C. 拒否する", "D. 飾り付ける"], "B",
     ["A. declare", "B. decline", "C. decorate", "D. decrease"], "A",
     "The president declared a state of emergency.（大統領が非常事態を宣言した。）",
     "He declared his intention to run for office.（彼は立候補する意思を宣言した。）"),
    ("deficit", "défəsit", "赤字", "B1",
     ["A. 赤字不足", "B. 限定版", "C. 明確化", "D. 反抗行為"], "A",
     ["A. deficit", "B. definite", "C. defense", "D. defiant"], "A",
     "The government is trying to reduce the deficit.（政府は赤字の削減を試みている。）",
     "The trade deficit has been growing.（貿易赤字が拡大している。）"),
    ("democracy", "dimɑ́krəsi", "民主主義", "B1",
     ["A. 民主主義", "B. 人口統計", "C. 解体作業", "D. 悪魔信仰"], "A",
     ["A. democracy", "B. diplomacy", "C. demography", "D. demolition"], "A",
     "Democracy gives power to the people.（民主主義は人々に権力を与える。）",
     "Japan has been a democracy since 1947.（日本は1947年以来民主主義国家だ。）"),
    ("demonstrate", "démənstrèit", "実演する", "B1",
     ["A. 実演する", "B. 要求する", "C. 破壊する", "D. 降格する"], "A",
     ["A. demonstrate", "B. denominate", "C. deteriorate", "D. depreciate"], "A",
     "Let me demonstrate how the machine works.（その機械の動き方を実演しましょう。）",
     "The teacher demonstrated the experiment.（先生が実験を実演した。）"),
    ("deny", "dinái", "否定する", "A2",
     ["A. 否定する", "B. 遅らせる", "C. 配達する", "D. 設計する"], "A",
     ["A. deny", "B. delay", "C. deliver", "D. design"], "A",
     "He denied the accusation.（彼はその告発を否定した。）",
     "She denied any involvement in the incident.（彼女はその事件への関与を否定した。）"),
    ("depict", "dipíkt", "描写する", "B1",
     ["A. 出発する", "B. 依存する", "C. 描写する", "D. 展開する"], "C",
     ["A. depict", "B. depart", "C. deploy", "D. deposit"], "A",
     "The painting depicts a rural landscape.（その絵画は田園風景を描写している。）",
     "The movie depicts life in ancient Rome.（その映画は古代ローマの生活を描写している。）"),
    ("derive", "diráiv", "由来する", "B1",
     ["A. 到着する", "B. 由来する", "C. 欺く騙す", "D. 装飾する"], "B",
     ["A. derive", "B. deprive", "C. deceive", "D. deserve"], "A",
     "The word derives from Latin.（その単語はラテン語に由来する。）",
     "We can derive meaning from context.（文脈から意味を導き出すことができる。）"),
    ("detect", "ditékt", "検出する", "B1",
     ["A. 検出する", "B. 拘留する", "C. 決定する", "D. 抑止する"], "A",
     ["A. detect", "B. detain", "C. detest", "D. deter"], "A",
     "The sensor can detect smoke.（センサーは煙を検出できる。）",
     "They detected a problem in the system.（システムの問題を検出した。）"),
    ("devote", "divóut", "捧げる", "B1",
     ["A. 開発する", "B. 逸脱する", "C. 捧げる専念", "D. 貪り食う"], "C",
     ["A. devote", "B. develop", "C. deviate", "D. devour"], "A",
     "She devoted her life to teaching.（彼女は教育に人生を捧げた。）",
     "He devotes three hours a day to practice.（彼は毎日3時間を練習に捧げている。）"),
    ("diminish", "dimíniʃ", "減少する", "B1",
     ["A. 減少する", "B. 解散する", "C. 区別する", "D. 配分する"], "A",
     ["A. diminish", "B. demolish", "C. distinguish", "D. distribute"], "A",
     "The population continues to diminish.（人口は減少し続けている。）",
     "His influence has diminished over the years.（彼の影響力は年々減少した。）"),
    ("disclose", "disklóuz", "暴露する", "B1",
     ["A. 閉じ込める", "B. 暴露する", "C. 割引する", "D. 発見する"], "B",
     ["A. disclose", "B. discount", "C. discover", "D. dissolve"], "A",
     "The company refused to disclose the information.（会社はその情報を暴露することを拒否した。）",
     "She disclosed the secret to her friend.（彼女は友人にその秘密を暴露した。）"),
    ("distinct", "distíŋkt", "明確な", "B1",
     ["A. 明確な異なる", "B. 距離の遠い", "C. 地区の範囲", "D. 苦痛の感覚"], "A",
     ["A. distant", "B. distinct", "C. district", "D. distress"], "B",
     "There is a distinct difference between the two.（二つの間には明確な違いがある。）",
     "Each region has its own distinct culture.（各地域には独自の明確な文化がある。）"),
    ("diverse", "daivə́ːrs", "多様な", "B1",
     ["A. 多様な", "B. 反対の", "C. 分割の", "D. 神聖な"], "A",
     ["A. diverse", "B. divert", "C. divide", "D. divine"], "A",
     "Tokyo is a diverse and multicultural city.（東京は多様で多文化な都市だ。）",
     "The team is diverse in terms of background.（そのチームは経歴の面で多様だ。）"),
    ("domestic", "dəméstik", "国内の", "B1",
     ["A. 支配的な", "B. 国内の", "C. 寄贈する", "D. 休眠中の"], "B",
     ["A. domestic", "B. dominant", "C. dormant", "D. dramatic"], "A",
     "Domestic flights are cheaper than international ones.（国内線は国際線より安い。）",
     "The domestic economy is recovering.（国内経済は回復している。）"),
    ("eager", "íːgər", "熱心な", "A2",
     ["A. 熱心な意欲", "B. 以前の時代", "C. 稼ぐ獲得", "D. 容易な手軽"], "A",
     ["A. eager", "B. early", "C. earth", "D. equal"], "A",
     "She is eager to learn new things.（彼女は新しいことを学ぶのに熱心だ。）",
     "The students are eager to start the project.（学生たちはプロジェクトを始めるのに熱心だ。）"),
    ("elaborate", "ilǽbərət", "精巧な", "B1",
     ["A. 精巧な詳細", "B. 選挙の公式", "C. 初等の基本", "D. 優雅な上品"], "A",
     ["A. elaborate", "B. eliminate", "C. elevate", "D. eloquent"], "A",
     "She wore an elaborate costume.（彼女は精巧な衣装を着ていた。）",
     "The plan was detailed and elaborate.（その計画は詳細で精巧だった。）"),
    ("embrace", "imbréis", "受け入れる", "B1",
     ["A. 困惑させる", "B. 受け入れる", "C. 出現する", "D. 緊急の状況"], "B",
     ["A. embarrass", "B. embrace", "C. emerge", "D. embark"], "B",
     "We should embrace new technology.（新しい技術を受け入れるべきだ。）",
     "She embraced the challenge with enthusiasm.（彼女は熱意を持ってその挑戦を受け入れた。）"),
    ("emerge", "imə́ːrdʒ", "現れる", "B1",
     ["A. 緊急に出る", "B. 現れ出る", "C. 合併する", "D. 移住する"], "B",
     ["A. emerge", "B. emergency", "C. emigrate", "D. embrace"], "A",
     "New evidence emerged during the investigation.（調査中に新しい証拠が現れた。）",
     "The sun emerged from behind the clouds.（太陽が雲の後ろから現れた。）"),
    ("endure", "indjúːr", "耐える", "B1",
     ["A. 確保する", "B. 耐え忍ぶ", "C. 巻き込む", "D. 楽しませる"], "B",
     ["A. endure", "B. ensure", "C. engage", "D. enforce"], "A",
     "She endured years of hardship.（彼女は何年もの苦難に耐えた。）",
     "Athletes must endure intense training.（アスリートは激しい訓練に耐えなければならない。）"),
    ("enhance", "inhǽns", "向上させる", "B1",
     ["A. 向上させる", "B. 強制する", "C. 楽しませる", "D. 保証する"], "A",
     ["A. enhance", "B. enforce", "C. enclose", "D. encrypt"], "A",
     "This feature enhances the user experience.（この機能はユーザー体験を向上させる。）",
     "Spices can enhance the flavor of food.（香辛料は食べ物の風味を向上させる。）"),
    ("enterprise", "éntərpràiz", "事業", "B1",
     ["A. 事業企業", "B. 娯楽施設", "C. 入場許可", "D. 全体概要"], "A",
     ["A. enterprise", "B. entertain", "C. entrance", "D. envelope"], "A",
     "She runs a small enterprise.（彼女は小さな事業を経営している。）",
     "Free enterprise is the basis of capitalism.（自由企業は資本主義の基盤だ。）"),
    ("era", "íːrə", "時代", "A2",
     ["A. 誤り間違", "B. 時代区分", "C. 地域範囲", "D. 消去作業"], "B",
     ["A. error", "B. era", "C. area", "D. erase"], "B",
     "We live in the digital era.（私たちはデジタル時代に生きている。）",
     "The Edo era lasted over 260 years.（江戸時代は260年以上続いた。）"),
    ("ethnic", "éθnik", "民族の", "B1",
     ["A. 倫理的な", "B. 民族的な", "C. 永遠の", "D. 熱心な"], "B",
     ["A. ethical", "B. ethnic", "C. eternal", "D. elegant"], "B",
     "Japan has a rich ethnic heritage.（日本は豊かな民族的遺産を持っている。）",
     "The city has many ethnic restaurants.（その都市には多くの民族料理のレストランがある。）"),
    ("exceed", "iksíːd", "超過する", "B1",
     ["A. 超過する", "B. 除外する", "C. 興奮させる", "D. 交換する"], "A",
     ["A. exceed", "B. except", "C. excite", "D. excuse"], "A",
     "Do not exceed the speed limit.（制限速度を超過しないでください。）",
     "Sales exceeded our expectations.（売上は我々の期待を超過した。）"),
    ("exploit", "ɪksplɔ́it", "利用する", "B1",
     ["A. 説明する", "B. 利用する", "C. 爆発する", "D. 探検する"], "B",
     ["A. exploit", "B. explore", "C. explode", "D. explain"], "A",
     "We should exploit renewable energy sources.（再生可能エネルギー源を利用すべきだ。）",
     "Don't exploit other people's kindness.（他人の親切を利用してはいけない。）"),
    ("expose", "ikspóuz", "さらす", "B1",
     ["A. さらす暴露", "B. 輸出する", "C. 拡大する", "D. 追放する"], "A",
     ["A. expose", "B. export", "C. expand", "D. expel"], "A",
     "Don't expose the film to sunlight.（フィルムを日光にさらさないでください。）",
     "The report exposed corruption in the government.（その報告書は政府の汚職をさらした。）"),
    ("extent", "ikstént", "程度", "B1",
     ["A. 程度範囲", "B. 拡大延長", "C. 外部要因", "D. 抽出方法"], "A",
     ["A. extent", "B. extend", "C. external", "D. extract"], "A",
     "To what extent do you agree?（どの程度同意しますか？）",
     "The extent of the damage was enormous.（損害の程度は甚大だった。）"),
    ("flourish", "flə́ːriʃ", "繁栄する", "B1",
     ["A. 繁栄する", "B. 蛍光を放つ", "C. 流暢に話す", "D. 変動する"], "A",
     ["A. flourish", "B. furnish", "C. foolish", "D. franchise"], "A",
     "The economy flourished under the new policy.（新しい政策の下で経済が繁栄した。）",
     "Plants flourish in warm, humid conditions.（植物は温暖で湿潤な条件で繁栄する。）"),
    ("fragment", "frǽgmənt", "断片", "B1",
     ["A. 断片の欠片", "B. 芳香の香り", "C. 骨折の部位", "D. 枠組み構造"], "A",
     ["A. fragment", "B. fragrance", "C. fracture", "D. framework"], "A",
     "Fragments of pottery were found at the site.（遺跡で陶器の断片が発見された。）",
     "Only a small fragment of the painting remains.（絵画のほんの小さな断片だけが残っている。）"),
    ("frontier", "frʌntíːr", "辺境", "B1",
     ["A. 辺境地域", "B. 前部正面", "C. 凍結状態", "D. 果物類"], "A",
     ["A. frontier", "B. friction", "C. fraction", "D. frequent"], "A",
     "Space is the final frontier.（宇宙は最後の辺境だ。）",
     "AI is at the frontier of technology.（AIは技術の辺境にある。）"),
    ("fulfill", "fulfíl", "果たす", "B1",
     ["A. 果たす達成", "B. 燃料を入れる", "C. 楽しませる", "D. 機能する"], "A",
     ["A. fulfill", "B. furnish", "C. function", "D. forecast"], "A",
     "She fulfilled her promise.（彼女は約束を果たした。）",
     "He worked hard to fulfill his dream.（彼は夢を果たすために懸命に働いた。）"),
    ("genuine", "dʒénjuin", "本物の", "B1",
     ["A. 一般的な", "B. 寛大な", "C. 本物の真の", "D. 穏やかな"], "C",
     ["A. genuine", "B. generous", "C. genetic", "D. general"], "A",
     "This is a genuine leather bag.（これは本物の革のカバンだ。）",
     "Her smile was warm and genuine.（彼女の笑顔は温かく本物だった。）"),
    ("grant", "grǽnt", "付与する", "B1",
     ["A. 付与する", "B. 偉大にする", "C. 握る掴む", "D. 嘆き悲しむ"], "A",
     ["A. grand", "B. grant", "C. grasp", "D. grind"], "B",
     "The university granted her a scholarship.（大学は彼女に奨学金を付与した。）",
     "Permission was granted to enter the building.（建物への入場許可が付与された。）"),
    ("guarantee", "gæ̀rəntíː", "保証する", "A2",
     ["A. 保護する", "B. 案内する", "C. 保証する", "D. 推測する"], "C",
     ["A. guarantee", "B. guardian", "C. guideline", "D. graduate"], "A",
     "We guarantee the quality of our products.（製品の品質を保証します。）",
     "There is no guarantee of success.（成功の保証はない。）"),
    ("guilty", "gílti", "有罪の", "A2",
     ["A. 有罪の責任", "B. 案内の役割", "C. 罪悪の感覚", "D. 湾岸の地域"], "A",
     ["A. guilty", "B. guitar", "C. guest", "D. guard"], "A",
     "The jury found him guilty.（陪審員は彼を有罪と認定した。）",
     "She felt guilty about lying.（彼女は嘘をついたことに罪悪感を感じた。）"),
    ("harbor", "hɑ́ːrbər", "港", "A2",
     ["A. 港の施設", "B. 困難な状況", "C. 収穫の時期", "D. 調和の状態"], "A",
     ["A. harbor", "B. hardship", "C. harvest", "D. harmony"], "A",
     "The ship entered the harbor at dawn.（船は夜明けに港に入った。）",
     "The harbor was full of fishing boats.（港は漁船でいっぱいだった。）"),
    ("harsh", "hɑ́ːrʃ", "厳しい", "A2",
     ["A. 厳しい過酷", "B. 急いで慌て", "C. 心から温か", "D. 嫌がる憎む"], "A",
     ["A. harsh", "B. hasty", "C. hatred", "D. health"], "A",
     "The winter weather was harsh.（冬の天気は厳しかった。）",
     "His words were too harsh.（彼の言葉は厳しすぎた。）"),
    ("horizon", "həráizn", "地平線", "A2",
     ["A. 恐怖の感情", "B. 地平線水平", "C. 馬の乗り物", "D. 名誉の気持"], "B",
     ["A. horizon", "B. horrible", "C. hormone", "D. hostage"], "A",
     "The sun set below the horizon.（太陽が地平線の下に沈んだ。）",
     "We could see the mountains on the horizon.（地平線上に山が見えた。）"),
    ("identical", "aidéntikəl", "同一の", "B1",
     ["A. 理想的な", "B. 同一の", "C. 特定する", "D. 個性ある"], "B",
     ["A. identical", "B. idealistic", "C. identify", "D. ideology"], "A",
     "The twins look identical.（双子は同一に見える。）",
     "The two dresses are identical.（その二つのドレスは同一だ。）"),
    ("illusion", "ilúːʒən", "錯覚", "B1",
     ["A. 挿絵図解", "B. 錯覚幻想", "C. 照明機材", "D. 暗示示唆"], "B",
     ["A. illustration", "B. illusion", "C. illuminate", "D. implication"], "B",
     "The mirror created an optical illusion.（鏡が光学的な錯覚を生み出した。）",
     "Freedom without responsibility is an illusion.（責任のない自由は錯覚だ。）"),
    ("impose", "impóuz", "課す", "B1",
     ["A. 輸入する", "B. 課す強制する", "C. 印象を与える", "D. 改善する"], "B",
     ["A. import", "B. impose", "C. impress", "D. improve"], "B",
     "The government imposed new taxes.（政府が新しい税金を課した。）",
     "I don't want to impose on your hospitality.（あなたのおもてなしに付け込みたくない。）"),
    ("incentive", "inséntiv", "奨励", "B1",
     ["A. 奨励動機付", "B. 事件の出来", "C. 偶然の機会", "D. 費用の支出"], "A",
     ["A. incentive", "B. incident", "C. incidence", "D. inclusive"], "A",
     "The company offers incentives for hard work.（その会社は勤勉さに対して奨励を提供する。）",
     "Tax incentives attract foreign investment.（税制上の奨励が外国投資を引き付ける。）"),
    ("incorporate", "inkɔ́ːrpərèit", "組み入れる", "B1",
     ["A. 組み入れる", "B. 正しくない", "C. 増加させる", "D. 自立させる"], "A",
     ["A. incorporate", "B. incorrect", "C. incredible", "D. independent"], "A",
     "We will incorporate your feedback.（あなたのフィードバックを組み入れます。）",
     "The design incorporates traditional elements.（そのデザインは伝統的な要素を組み入れている。）"),
    ("inhabit", "inhǽbit", "住む", "B1",
     ["A. 住む居住する", "B. 抑制する禁止", "C. 相続する遺産", "D. 始める開始"], "A",
     ["A. inhabit", "B. inhibit", "C. inherit", "D. initial"], "A",
     "Many species inhabit this forest.（多くの種がこの森に住んでいる。）",
     "Humans have inhabited this area for thousands of years.（人間は何千年もこの地域に住んでいる。）"),
    ("inherit", "inhérit", "相続する", "B1",
     ["A. 住む居住する", "B. 相続する", "C. 始める開始", "D. 抑制する禁止"], "B",
     ["A. inhabit", "B. inherit", "C. initial", "D. inhibit"], "B",
     "She inherited the house from her grandmother.（彼女は祖母からその家を相続した。）",
     "He inherited his father's business.（彼は父親の事業を相続した。）"),
    ("innovate", "ínəvèit", "革新する", "B1",
     ["A. 革新する", "B. 侵入する", "C. 調査する", "D. 招待する"], "A",
     ["A. innovate", "B. invade", "C. investigate", "D. intimidate"], "A",
     "Companies must innovate to stay competitive.（企業は競争力を保つために革新しなければならない。）",
     "We need to innovate our approach.（アプローチを革新する必要がある。）"),
    ("insight", "ínsàit", "洞察", "B1",
     ["A. 洞察力理解", "B. 主張要求", "C. 代わりの案", "D. 本能的直感"], "A",
     ["A. insight", "B. insist", "C. instead", "D. instinct"], "A",
     "The book offers valuable insights into Japanese culture.（その本は日本文化への貴重な洞察を提供する。）",
     "Her insight into the problem was impressive.（問題への彼女の洞察は印象的だった。）"),
    ("integral", "íntəgrəl", "不可欠な", "B1",
     ["A. 不可欠な", "B. 知的な", "C. 意図的な", "D. 集中的な"], "A",
     ["A. integral", "B. intellect", "C. interact", "D. internal"], "A",
     "Teamwork is integral to success.（チームワークは成功に不可欠だ。）",
     "Music is an integral part of the festival.（音楽はその祭りの不可欠な部分だ。）"),
    ("intervene", "ìntərvíːn", "介入する", "B1",
     ["A. 面接する", "B. 介入する", "C. 発明する", "D. 投資する"], "B",
     ["A. interview", "B. intervene", "C. invent", "D. invest"], "B",
     "The government decided to intervene in the crisis.（政府は危機に介入することを決めた。）",
     "Sometimes it is necessary to intervene.（介入が必要な場合もある。）"),
    ("inventory", "ínvəntɔ̀ːri", "在庫", "B1",
     ["A. 在庫品目", "B. 発明発見", "C. 投資案件", "D. 招待状類"], "A",
     ["A. inventory", "B. invention", "C. investor", "D. invasion"], "A",
     "We need to check the inventory.（在庫を確認する必要がある。）",
     "The store's inventory is running low.（その店の在庫が少なくなっている。）"),
]

# Check for duplicates with existing
new_word_list = [w[0] for w in new_words]
print(f"New words count: {len(new_words)}")

dupes_with_existing = [w for w in new_word_list if w in existing_words]
if dupes_with_existing:
    print(f"WARNING: Duplicates with existing: {dupes_with_existing}")

# Check internal duplicates
from collections import Counter
word_counts = Counter(new_word_list)
internal_dupes = {w: c for w, c in word_counts.items() if c > 1}
if internal_dupes:
    print(f"WARNING: Internal duplicates: {internal_dupes}")

# Generate questions
new_questions = []
q_id = 501
answer_counts = {"A": 0, "B": 0, "C": 0, "D": 0}

for word_data in new_words:
    word, pron, ja_meaning, level, en_ja_choices, en_ja_ans, ja_en_choices, ja_en_ans, en_ja_ex, ja_en_ex = word_data

    search_url = f"https://www.google.com/search?q={word}+meaning"
    translate_url = f"https://translate.google.co.jp/details?sl=en&tl=ja&text={urllib.parse.quote(word)}&op=translate"

    # en_to_ja question
    en_to_ja = {
        "id": f"eng_{q_id:03d}",
        "level": level,
        "pattern": "en_to_ja",
        "question": f"\"{word}\" の意味は？",
        "choices": en_ja_choices,
        "answer": en_ja_ans,
        "explanation": f"{word} = {ja_meaning}。例: {en_ja_ex}",
        "word": word,
        "pronunciation": pron,
        "reviewed": True,
        "enabled": True,
        "search_url": search_url,
        "translate_url": translate_url
    }
    new_questions.append(en_to_ja)
    answer_counts[en_ja_ans] += 1
    q_id += 1

    # ja_to_en question
    ja_to_en = {
        "id": f"eng_{q_id:03d}",
        "level": level,
        "pattern": "ja_to_en",
        "question": f"「{ja_meaning}」を英語で言うと？",
        "choices": ja_en_choices,
        "answer": ja_en_ans,
        "explanation": f"{word} = {ja_meaning}。例: {ja_en_ex}",
        "word": word,
        "pronunciation": pron,
        "reviewed": True,
        "enabled": True,
        "search_url": search_url,
        "translate_url": translate_url
    }
    new_questions.append(ja_to_en)
    answer_counts[ja_en_ans] += 1
    q_id += 1

print(f"\nGenerated {len(new_questions)} new questions")
print(f"ID range: eng_501 to eng_{q_id - 1:03d}")

# Level distribution
a2_words = set()
b1_words = set()
for w in new_words:
    if w[3] == "A2":
        a2_words.add(w[0])
    else:
        b1_words.add(w[0])
print(f"A2 words: {len(a2_words)}, B1 words: {len(b1_words)}")

# Answer distribution
print(f"Answer distribution (en_to_ja + ja_to_en combined): {answer_counts}")

# Combine
all_questions = existing + new_questions
data["questions"] = all_questions
print(f"\nTotal questions in file: {len(all_questions)}")

# Write
with open("C:/Users/user/kotohira-quiz/web/public/data/english_questions.json", "w", encoding="utf-8") as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print("File written successfully!")
